9 resposive header and footer
TechStreamConference/website-frontend pull request #13
Opened 2024-08-30 16:30 UTC by PurpurTentakel97

close #9 
see #12

2024-08-30 17:36 UTC, mgerhold requested changes
My impressions and findings so far:

- In the mobile view, the black line under the header is missing. That can lead to the header and footer "becoming one".
![image](https://github.com/user-attachments/assets/c771e27c-9c25-43ab-9735-98bbde56d486)
- In general I'd suggest making that black border smaller (maybe only 1 or 2 pixels).
- I'd like a smaller offset when jumping to an anchor mark. I know that you don't want the heading to be "smashed" against the top, but at the moment I think the offset is a bit too big.
- When using a mobile phone in landscape mode, the hamburger menu doesn't fit the screen. I think we either need a scrollbar or two columns.

2024-08-30 17:36 UTC, mgerhold commented on src/elements/header.svelte
> +		const colapse = () => {
typo
```suggestion
		const collapse = () => {
```

2024-08-30 17:36 UTC, mgerhold commented on src/elements/header.svelte
> +		window.addEventListener('scroll', colapse);
I think this is a cool idea, but when interacting with the website it felt a bit weird to me. I would not expect the menu to close (maybe because I'm not used to it, judging from other websites). Maybe we should ask someone with more experience with UI/UX?

2024-08-30 20:48 UTC, PurpurTentakel97 commented on src/elements/header.svelte
> +		window.addEventListener('scroll', colapse);
My idea was that when you scroll your focus is clearly on the side behind the menu.
So collapsing the menu was logical to me.  maybe even when you choose a menu point. what do you think?

2024-08-30 20:53 UTC, PurpurTentakel97 commented on src/elements/header.svelte
> +		const colapse = () => {
done

2024-08-30 20:55 UTC, PurpurTentakel97 commented on src/elements/header.svelte
> +		window.addEventListener('scroll', colapse);
But I agree. On Desktop it feels verry weird.
Maybe one would need to try it on mobile at this point.

2024-08-31 10:51 UTC, mgerhold commented on src/elements/header.svelte
> +		window.addEventListener('scroll', colapse);
I talked to the chat about this. We all think that closing the menu on scroll is okay, but only if the scrolling starts outside of the expanded menu. But when the cursor (or finger, on mobile) starts dragging on the menu, the menu should not be closed.

Another idea is: If you start scrolling on the expanded menu and you move the cursor/finger upwards, then the menu could collapse accordingly. And if you keep dragging until less than half of the menu is still visible, then the menu could "auto-collapse" the rest of the animation.

2024-08-31 10:52 UTC, peddermaster2 commented on src/elements/header.svelte
> +		window.addEventListener('scroll', colapse);
I have to agree with @mgerhold

2024-08-31 11:06 UTC, mgerhold requested changes
The hamburger symbol animation seems to be a bit off now. The "X" symbol is positioned a little bit to the left compared to the three hamburger slices:
![image](https://github.com/user-attachments/assets/f0655d24-59ee-4adf-9075-42e9dd739c88)
I don't think that it already was like this before your latest pushes.

2024-08-31 16:34 UTC, mgerhold approved these changes

2024-08-31 16:41 UTC, merged