Propz
TechStreamConference/website-frontend pull request #48
Opened 2024-09-28 14:34 UTC by PurpurTentakel97

close #47 
close #45 
close #41

2024-09-28 18:27 UTC, peddermaster2 requested changes

2024-09-28 18:27 UTC, peddermaster2 commented on src/elements/person/personRectangle.svelte
>  	}
Test successful?

2024-09-28 18:27 UTC, peddermaster2 commented on src/elements/section/section.svelte
> +        scroll-margin-top: 7rem;
formatting

2024-09-28 18:27 UTC, peddermaster2 commented on src/lookup/iconLookup.ts
> +    return lookup['web'];
```suggestion
    return lookup['Web'];
```

2024-09-28 19:14 UTC, PurpurTentakel97 commented on src/elements/person/personRectangle.svelte
>  	}
actually no.
see #46 

but I will rename that anyway. 🙈

2024-09-28 19:17 UTC, PurpurTentakel97 commented on src/elements/section/section.svelte
> +        scroll-margin-top: 7rem;
funny. In my local branch it is not like this.

2024-09-28 19:18 UTC, PurpurTentakel97 commented on src/lookup/iconLookup.ts
> +    return lookup['web'];
Ah thats why the fallback did not work. 🙈

2024-09-28 19:28 UTC, peddermaster2 approved these changes
I got no more notes 👍🏻

2024-09-29 15:16 UTC, peddermaster2 approved these changes

2024-09-29 15:54 UTC, mgerhold requested changes
Grammar check completed 😅

2024-09-29 15:54 UTC, mgerhold commented on src/menu/impressum.ts
> +        description: 'Klicke hier um zur aktuellen Hauptseite zurückzukehren'
```suggestion
        description: 'Klicke hier, um zur aktuellen Hauptseite zurückzukehren'
```

2024-09-29 15:54 UTC, mgerhold commented on src/menu/impressum.ts
> +        description: 'Klicke hier zum anmelden'
```suggestion
        description: 'Klicke hier zum Anmelden'
```

2024-09-29 15:54 UTC, mgerhold commented on src/menu/impressum.ts
> +        description: 'Klicke hier zum registrieren'
```suggestion
        description: 'Klicke hier zum Registrieren'
```

2024-09-29 15:54 UTC, mgerhold commented on src/menu/impressum.ts
> +        description: 'Klicke hier um zur aktuellen Hauptseite zurückzukehren'
```suggestion
        description: 'Klicke hier, um zur aktuellen Hauptseite zurückzukehren'
```

2024-09-29 15:54 UTC, mgerhold commented on src/menu/impressum.ts
> +        description: 'Klicke hier zum abmelden'
```suggestion
        description: 'Klicke hier zum Abmelden'
```

2024-09-29 15:54 UTC, mgerhold commented on src/menu/impressum.ts
> +        description: 'Klicke hier um zur aktuellen Hauptseite zurückzukehren'
```suggestion
        description: 'Klicke hier, um zur aktuellen Hauptseite zurückzukehren'
```

2024-09-29 15:54 UTC, mgerhold commented on src/menu/impressum.ts
> +        description: 'Klicke hier zum anmelden'
```suggestion
        description: 'Klicke hier zum Anmelden'
```

2024-09-29 15:54 UTC, mgerhold commented on src/menu/impressum.ts
> +        description: 'Klicke hier zum registrieren'
```suggestion
        description: 'Klicke hier zum Registrieren'
```

2024-09-29 15:54 UTC, mgerhold commented on src/menu/impressum.ts
> +        description: 'Klicke hier um zur aktuellen Hauptseite zurückzukehren'
```suggestion
        description: 'Klicke hier, um zur aktuellen Hauptseite zurückzukehren'
```

2024-09-29 15:54 UTC, mgerhold commented on src/menu/impressum.ts
> +        description: 'Klicke hier um in den internen Bereich zu gelangen'
```suggestion
        description: 'Klicke hier, um in den internen Bereich zu gelangen'
```

2024-09-29 15:54 UTC, mgerhold commented on src/menu/login.ts
I don't want to spam too many comments, but this and also other files contain the same or similar typos like the previous file.

2024-09-29 15:54 UTC, mgerhold commented on src/routes/impressum/+page.svelte
I just realise that "impressum" is German 😅 It should be "imprint" instead (just for consistency).

2024-09-29 15:54 UTC, mgerhold commented on src/routes/impressum/+page.svelte
> +				title="Klicke hier um uns eine Mail zu schreiben">info@test-conf.de</Link
```suggestion
				title="Klicke hier, um uns eine Mail zu schreiben">info@test-conf.de</Link
```

2024-09-29 15:54 UTC, mgerhold commented on src/routes/impressum/+page.svelte
> +				title="Klicke hier um dich über die Europäische
```suggestion
				title="Klicke hier, um dich über die Europäische
```

2024-09-29 15:54 UTC, mgerhold commented on src/routes/impressum/+page.svelte
> +				title="Klicke hier um uns eine Mail zu schreiben"
```suggestion
				title="Klicke hier, um uns eine Mail zu schreiben"
```

2024-09-29 15:54 UTC, mgerhold commented on src/routes/impressum/+page.svelte
> +		<SubHeadline classes="imperssum-subheadline">Disclaimer – rechtliche Hinweise</SubHeadline>
```suggestion
		<SubHeadline classes="impressum-subheadline">Disclaimer – rechtliche Hinweise</SubHeadline>
```

or rather

`imprint-subheadline`

2024-09-29 15:54 UTC, mgerhold commented on src/routes/impressum/+page.svelte
>  			§ 4 Besondere Nutzungsbedingungen Soweit besondere Bedingungen für einzelne Nutzungen dieser
Shouldn't there be a linebreak after "Nutzungsbedingungen"?

2024-09-29 15:54 UTC, mgerhold commented on src/routes/impressum/+page.svelte
> +				title="Klicke hier um dich über besondere Nutzungsbedingungen zu informieren"
```suggestion
				title="Klicke hier, um zur Quelle dieses Online-Impressums zu gelangen"
```

2024-09-29 15:54 UTC, mgerhold commented on src/routes/register/+page.svelte
> +					ariaLabel="Gebe den Nutzernamen ein"
```suggestion
					ariaLabel="Gib den Nutzernamen ein"
```

2024-09-29 15:54 UTC, mgerhold commented on src/routes/register/+page.svelte
> +					ariaLabel="Gebe die E-Mail ein"
```suggestion
					ariaLabel="Gib die E-Mail ein"
```

2024-09-29 15:54 UTC, mgerhold commented on src/routes/register/+page.svelte
> +					ariaLabel="Gebe das passwort ein"
```suggestion
					ariaLabel="Gib das Passwort ein"
```

2024-09-29 15:54 UTC, mgerhold commented on src/routes/register/+page.svelte
> +					ariaLabel="Wiederhole das Password"
```suggestion
					ariaLabel="Wiederhole das Passwort"
```

2024-09-29 15:54 UTC, mgerhold commented on src/routes/register/+page.svelte
> +				<Button
I think there's too much free space between the input fields and the button.

2024-09-29 15:54 UTC, mgerhold commented on src/routes/register/+page.svelte
> +						<Button ariaLabel="Klicke um zur aktuellen Hauptseite zu gelangen">Start</Button>
```suggestion
						<Button ariaLabel="Klicke, um zur aktuellen Hauptseite zu gelangen">Start</Button>
```

2024-09-29 15:54 UTC, mgerhold commented on src/routes/register/+page.svelte
> +						<Button ariaLabel="Klicke um dich anzumelden">Anmelden</Button>
```suggestion
						<Button ariaLabel="Klicke, um dich anzumelden">Anmelden</Button>
```

2024-09-29 16:14 UTC, PurpurTentakel97 commented on src/menu/login.ts
I hope I found all. 🙈

2024-09-29 17:26 UTC, mgerhold requested changes

2024-09-29 17:26 UTC, mgerhold commented on src/menu/menuItems.ts
> +    description: 'Klicke, um zum Abmelden'
```suggestion
    description: 'Klicke zum Abmelden'
```

2024-09-29 17:26 UTC, mgerhold commented on src/menu/menuItems.ts
> +    description: 'Klicke, um zum Anmelden'
```suggestion
    description: 'Klicke zum Anmelden'
```

2024-09-29 17:26 UTC, mgerhold commented on src/menu/menuItems.ts
> +    description: 'Klicke, zum registrieren'
```suggestion
    description: 'Klicke zum Registrieren'
```

2024-09-29 17:26 UTC, mgerhold commented on src/menu/menuItems.ts
> +    description: 'Klicke, um zum impressum zu gelangen'
```suggestion
    description: 'Klicke, um zum Impressum zu gelangen'
```

2024-09-29 17:26 UTC, mgerhold commented on src/routes/login/+page.svelte
> +			<Button classes="text login-submit-button" type="submit" ariaLabel="Klicke, zum Anmelden">
```suggestion
			<Button classes="text login-submit-button" type="submit" ariaLabel="Klicke zum Anmelden">
```

2024-09-29 17:26 UTC, mgerhold commented on src/routes/register/+page.svelte
> +					ariaLabel="Klicke, zum Registrieren"
```suggestion
					ariaLabel="Klicke zum Registrieren"
```

2024-09-29 17:34 UTC, mgerhold approved these changes

2024-09-29 17:34 UTC, merged