Footer
TechStreamConference/website-frontend pull request #6
Opened 2024-08-25 18:21 UTC by PurpurTentakel97

2024-08-25 19:07 UTC, mgerhold requested changes
All in all I think the footer looks good, but I think the font should be smaller and the margins (or paddings?) can be smaller.
![image](https://github.com/user-attachments/assets/f881277f-060a-4b69-86da-cb01caacb6f1)
So I think all texts in the footer (and the logo) should be smaller, but the copyright notice should be even *more* small than the rest. What do you think?

2024-08-25 19:07 UTC, mgerhold commented on src/routes/impressum/+page.svelte
> +<h1>Bestes Impressum. Also wirklich.</h1>
missing newline at end of file (you can set VSCode to always end files with a newline upon save)

2024-08-25 19:07 UTC, mgerhold commented on static/Style.css
> +}
missing newline

2024-08-25 19:35 UTC, PurpurTentakel97 commented on src/elements/footer.svelte
> +			<p class="YearHeadline">Alle Test-Conf:</p>
done

2024-08-25 19:37 UTC, PurpurTentakel97 commented on static/Style.css
> +}
The formatter does not add a newline here.
Diese nicht gut. 😅

2024-08-25 19:38 UTC, mgerhold commented on static/Style.css
> +}
Correct, diese schlecht 😂

2024-08-25 19:40 UTC, mgerhold approved these changes
Nice work! 👍

2024-08-25 19:41 UTC, merged

2024-08-26 06:22 UTC, peddermaster2 commented on src/elements/footer.svelte
> +		<img src={"/logo_big.png"} alt="The big Test-Conf logo. It shows the name on black clouds. Black lines emerge from the clouds with yellow dots at the ends. They look like circuits."/>
In einer deutschen Seite, sollten auch die alt Texte in deutsch sein.

2024-08-26 18:12 UTC, PurpurTentakel97 commented on src/elements/footer.svelte
> +		<img src={"/logo_big.png"} alt="The big Test-Conf logo. It shows the name on black clouds. Black lines emerge from the clouds with yellow dots at the ends. They look like circuits."/>
see #8 
I will close this.