60 use svelte for 404 page
TechStreamConference/website-frontend pull request #61
Opened 2024-10-10 20:06 UTC by PurpurTentakel97

close #60 

adds a small zoom effect for sponsors ans media partners (already approved)

add a "real" error page that gets displayed for all svelte errors.
also throw errors instead of redirecting to custom 404 page.

2024-10-11 14:39 UTC, mgerhold requested changes

2024-10-11 14:39 UTC, mgerhold commented on src/routes/+error.svelte
> +		<HeadlinePage classes="border">{$page.status}</HeadlinePage>
I think we should use the status code and perform a lookup to show a German error message, e.g. "Uuups! Die Seite konnte nicht gefunden werden 👻"

2024-10-11 14:39 UTC, mgerhold commented on src/routes/+error.svelte
> +			Hauptseite
On all other pages, you call this "Start", but here you call it "Hauptseite". I'm not sure which I like more (I always thought that "Start" is a bit weird), but at least it should be harmonized across all pages.

2024-10-11 14:39 UTC, mgerhold commented on src/routes/year/[year]/+page.ts
> +        throw error(404, `in der URL angegebenes Jahr "${params.year}" ist keine Zahl.`);
I don't think we need error messages that are this specific. For the user this should just show that the page doesn't exist (404 with a general-purpose error message).

2024-10-11 14:39 UTC, mgerhold commented on src/routes/year/[year]/year.ts
> +        throw error(400, `Unerwartete Daten für das Jahr ${year}.`)
Same here: I think those error messages are too specific to show them to the user. They are interesting for us (so maybe `console.error()` would be useful here?), but the user should just see a general 404 error message.

2024-10-11 17:51 UTC, PurpurTentakel97 commented on src/routes/+error.svelte
> +		<HeadlinePage classes="border">{$page.status}</HeadlinePage>
Would you only do that for 404?
The user will not see any other code or there is a serious issue.

What do you think?

2024-10-11 17:52 UTC, PurpurTentakel97 commented on src/routes/+error.svelte
> +			Hauptseite
So I turn it to "Hauptseite" then? :)

2024-10-11 17:53 UTC, PurpurTentakel97 commented
Im thinking about a "contact us" `mail to` Link.
What do you think?

But I don't know what mail I should display.

2024-10-11 18:08 UTC, mgerhold commented on src/routes/+error.svelte
> +		<HeadlinePage classes="border">{$page.status}</HeadlinePage>
Yes, then let's only do an error message for 404. We could also do another message for *any other* error, e.g. "Uuuups, irgendwas ist mächtig schief gelaufen, sorry! 🫨"

(the cringy emojis are very important Kappa)

2024-10-11 18:09 UTC, mgerhold commented on src/routes/+error.svelte
> +			Hauptseite
Would "Hauptseite" fit into the header on all pages? Even on mobile? I don't know. On the other hand: Maybe we could remove it from the header altogether and only use the logo (in the upper left corner) as a link to the main page. What do you think?

2024-10-11 18:10 UTC, mgerhold commented
> Im thinking about a "contact us" `mail to` Link. What do you think?
> 
> But I don't know what mail I should display.

You mean on the error page? Wouldn't a general contact page be enough? I don't think that the error page needs that feature.

2024-10-11 19:38 UTC, PurpurTentakel97 commented on src/routes/+error.svelte
> +			Hauptseite
The logo is already a shortcut for that.

Right now it is fitting inside the header.
On mobile even better ;)

Check it out and let me know.
For me its okay as it is now. :)

2024-10-12 20:14 UTC, mgerhold commented on src/routes/+error.svelte
> +			Hauptseite
But now it says "Top" instead of "Hauptseite" 🤔
![image](https://github.com/user-attachments/assets/71d11e5f-dae6-4285-8f02-83389458657d)
Is this intended?

2024-10-12 20:17 UTC, mgerhold requested changes
As I wrote in the other comment, on the main page the nav bar now shows "Top" instead of "Hauptseite". The rest is good 👍

2024-10-12 20:17 UTC, mgerhold commented on src/routes/+error.svelte
> +					Uuuups, irgendwas ist mächtig schief gelaufen, sorry! 🫨
Cringe! I like it! <3

2024-10-13 10:28 UTC, PurpurTentakel97 commented
You did not get that quite right.
"Top" was always "Top".
But I changed "Start" to "Hauptseite"

"Top" and "Hauptseite" does not do the same.
"Hauptseite" navigates to the main page of the current year.
"Top" scrolls to the top of the displayed year.
Therefore I would not name that the same.
When the current year and the displayed year is the same. Both do the same. But when they differ. "Hauptseite" loads an other page while "Top" does not.


But I see that the naming "Top" is not the yellow from the egg.
I don't like that ether.
But I don't know how else to name it. 😅

2024-10-13 15:40 UTC, mgerhold commented
Ah okay, now I get it. Then I will approve the PR for now. But I don't really like "Top" there. Maybe we should just show an arrow pointing upwards in a box, e.g. on the right side of the page. The box could be invisible when the user is already at the top and become visible when they scroll down.

2024-10-13 15:41 UTC, mgerhold approved these changes

2024-10-13 15:54 UTC, merged